- name: Render namespace configuration manifest
  template:
    src: kube-default-namespaces.j2
    dest: "{{ kubernetes_config_dir }}/kube-default-namespaces.yaml"
    mode: 0644
    owner: root
    group: root

- name: Setup Kubernetes Namespaces
  command: kubectl apply -f "{{ kubernetes_config_dir }}/kube-default-namespaces.yaml" {{kubectl_args|default()}}
  when: not is_packer|bool
